config/routes.rb
Classy::Application.routes.draw do
  resources :notices

  resources :feedbacks
  post 'feedbacks/submit' => 'feedbacks#submit'

  root :to => 'feedbacks#index'

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  attr_accessible :message, :source

  def send_sms(message)
    account_sid = "AC84038911e2045f80d19972f1aa6e5c6b"
    auth_token = "8a4e932b263e316391cfaee5df39dd3a"
    client = Twilio::REST::Client.new account_sid, auth_token

    from = "+16467620474" # Your Twilio number

    friends = {
        "+19174533751" => "EC",
        # "+1646-400-8497" => "SJ"
    }
    friends.each do |key, value|
      client.account.sms.messages.create(
          :from => from,
          :to => key,
          :body => "Hey #{value}, " + message
      )
      puts "Sent message to #{value}"
    end

  end

  def send_reply(caller, message)
    account_sid = "AC84038911e2045f80d19972f1aa6e5c6b"
    auth_token = "8a4e932b263e316391cfaee5df39dd3a"
    client = Twilio::REST::Client.new account_sid, auth_token

    from = "+16467620474" # Your Twilio number

    client.account.sms.messages.create(
        :from => from,
        :to => caller,
        :body => "Hey there, " + message + "was really great to have, thanks!"
    )
    puts "Sent message to #{value}"
  end

end

app/models/notice.rb
class Notice < ActiveRecord::Base
  attr_accessible :destination, :message, :note

  def self.send_notice(caller, message)
    account_sid = "AC84038911e2045f80d19972f1aa6e5c6b"
    auth_token = "8a4e932b263e316391cfaee5df39dd3a"
    client = Twilio::REST::Client.new account_sid, auth_token

    from = "+16467620474" # Your Twilio number

    client.account.sms.messages.create(
        :from => from,
        :to => caller,
        :body => message
    )
    puts "Sent message as requested"
    return
  end

  def send_sms(message)
    account_sid = "AC84038911e2045f80d19972f1aa6e5c6b"
    auth_token = "8a4e932b263e316391cfaee5df39dd3a"
    client = Twilio::REST::Client.new account_sid, auth_token

    from = "+16467620474" # Your Twilio number

    friends = {
        "+19174533751" => "EC",
        # "+1646-400-8497" => "SJ"
    }
    friends.each do |key, value|
      client.account.sms.messages.create(
          :from => from,
          :to => key,
          :body => "Hey #{value}, " + message
      )
      puts "Sent message to #{value}"
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedbacks }
    end
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/new
  # GET /feedbacks/new.json
  def new
    @feedback = Feedback.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/1/edit
  def edit
    @feedback = Feedback.find(params[:id])
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(params[:feedback])

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: 'Feedback was successfully created.' }
        format.json { render json: @feedback, status: :created, location: @feedback }
      else
        format.html { render action: "new" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST submit.html.erb
  def submit
      twiml = Twilio::TwiML::Response.new do |r|
        r.Message "Hey there, Thx 4 feedback! Your no #{params[:From]} is now in the system! And #{params[:Body]} is really helpful input.  We hope it's nice in #{params[:FromCity]}"
      end

      @feedback = Feedback.new({:source => params[:From], :message => params[:Body], :msid => params[:MessageSid], :zip => params[:FromZip]})
      logger.debug @feedback.to_s
      @feedback.save
      render :text => twiml.text

  end
  # PUT /feedbacks/1
  # PUT /feedbacks/1.json
  def update
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      if @feedback.update_attributes(params[:feedback])
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to feedbacks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notices }
    end
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
    @notice = Notice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notice }
    end
  end

  # GET /notices/new
  # GET /notices/new.json
  def new
    @notice = Notice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notice }
    end
  end

  # GET /notices/1/edit
  def edit
    @notice = Notice.find(params[:id])
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(params[:notice])
    puts @notice
    @notice.save
        # logger.debug "XOXOXOXOXOXOXOXOXO destination is " + @notice.destination + "and message is " + @notice.message
    Notice.last.send_notice(@notice.destination, @notice.message)
    format.html { redirect_to @notice, notice: 'Notice was successfully sent.' }
  end

  # PUT /notices/1
  # PUT /notices/1.json
  def update
    @notice = Notice.find(params[:id])

    respond_to do |format|
      if @notice.update_attributes(params[:notice])
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice = Notice.find(params[:id])
    @notice.destroy

    respond_to do |format|
      format.html { redirect_to notices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<h1>Feedback Submissions</h1>

<table>
  <tr>
    <th>Source</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
    <th>ID</th>
    <th>Zip Code</th>
    <th></th>
  </tr>

<% @feedbacks.each do |feedback| %>
  <tr>
    <td><%= feedback.source %></td>
    <td><%= feedback.message %></td>
    <td><%= feedback.msid %></td>
    <td><%= feedback.zip %></td>
    <td><%= link_to 'Show', feedback %></td>
    <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<!-- %= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Source:</b>
  <%= @feedback.source %>
</p>

<p>
  <b>Message:</b>
  <%= @feedback.message %>
</p>


<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/submit.html.erb
<h1>Listing feedbacks</h1>
         Params is <%= @params %>
<table>
    <tr>
        <th>Source</th>
        <th>Message</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>

    <% @feedbacks.each do |feedback| %>
    <tr>
        <td><%= feedback.source %></td>
        <td><%= feedback.message %></td>
        <td><%= link_to 'Show', feedback %></td>
        <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
        <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
</table>

<br />

<%= link_to 'New Feedback', new_feedback_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Classy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notices/_form.html.erb
<%= form_for(@notice) do |f| %>
  <% if @notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% @notice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :destination %><br />
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_field :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notices/edit.html.erb
<h1>Editing notice</h1>

<%= render 'form' %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/index.html.erb
<h1>Listing notices</h1>

<table>
  <tr>
    <th>Destination</th>
    <th>Message</th>
    <th>Note</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notices.each do |notice| %>
  <tr>
    <td><%= notice.destination %></td>
    <td><%= notice.message %></td>
    <td><%= notice.note %></td>
    <td><%= link_to 'Show', notice %></td>
    <td><%= link_to 'Edit', edit_notice_path(notice) %></td>
    <td><%= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Notice', new_notice_path %>

app/views/notices/new.html.erb
<h1>New notice</h1>

<%= render 'form' %>

<%= link_to 'Back', notices_path %>

app/views/notices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Destination:</b>
  <%= @notice.destination %>
</p>

<p>
  <b>Message:</b>
  <%= @notice.message %>
</p>

<p>
  <b>Note:</b>
  <%= @notice.note %>
</p>


<%= link_to 'Edit', edit_notice_path(@notice) %> |
<%= link_to 'Back', notices_path %>